const prisma = require("../prisma/client");

const categories = [
	{ "name": "Technology" },
	{ "name": "Software Development" },
	{ "name": "IT Support" },
	{ "name": "Data Science" },
	{ "name": "Cybersecurity" },
	{ "name": "Web Development" },
	{ "name": "Healthcare" },
	{ "name": "Nursing" },
	{ "name": "Medicine" },
	{ "name": "Pharmacy" },
	{ "name": "Physical Therapy" },
	{ "name": "Healthcare Administration" },
	{ "name": "Finance" },
	{ "name": "Accounting" },
	{ "name": "Financial Analysis" },
	{ "name": "Investment Banking" },
	{ "name": "Insurance" },
	{ "name": "Auditing" },
	{ "name": "Education" },
	{ "name": "Teaching" },
	{ "name": "Administration" },
	{ "name": "Curriculum Development" },
	{ "name": "Educational Technology" },
	{ "name": "Special Education" },
	{ "name": "Engineering" },
	{ "name": "Civil Engineering" },
	{ "name": "Mechanical Engineering" },
	{ "name": "Electrical Engineering" },
	{ "name": "Chemical Engineering" },
	{ "name": "Aerospace Engineering" },
	{ "name": "Marketing" },
	{ "name": "Digital Marketing" },
	{ "name": "Brand Management" },
	{ "name": "Market Research" },
	{ "name": "Content Creation" },
	{ "name": "Social Media Management" },
	{ "name": "Sales" },
	{ "name": "Business Development" },
	{ "name": "Account Management" },
	{ "name": "Retail Sales" },
	{ "name": "Inside Sales" },
	{ "name": "Outside Sales" },
	{ "name": "Human Resources" },
	{ "name": "Recruitment" },
	{ "name": "Employee Relations" },
	{ "name": "Compensation and Benefits" },
	{ "name": "Training and Development" },
	{ "name": "HR Administration" },
	{ "name": "Manufacturing" },
	{ "name": "Production Management" },
	{ "name": "Quality Control" },
	{ "name": "Supply Chain Management" },
	{ "name": "Logistics" },
	{ "name": "Assembly Line Work" },
	{ "name": "Creative Arts" },
	{ "name": "Graphic Design" },
	{ "name": "Photography" },
	{ "name": "Film and Video Production" },
	{ "name": "Music" },
	{ "name": "Writing and Editing" },
	{ "name": "Hospitality" },
	{ "name": "Hotel Management" },
	{ "name": "Food and Beverage Service" },
	{ "name": "Event Planning" },
	{ "name": "Travel and Tourism" },
	{ "name": "Customer Service" },
	{ "name": "Construction" },
	{ "name": "Project Management" },
	{ "name": "Site Management" },
	{ "name": "Skilled Trades" },
	{ "name": "Safety Management" },
	{ "name": "Estimation and Costing" },
	{ "name": "Legal" },
	{ "name": "Law Practice" },
	{ "name": "Paralegal Services" },
	{ "name": "Compliance" },
	{ "name": "Contract Management" },
	{ "name": "Legal Research" },
	{ "name": "Research and Development" },
	{ "name": "Scientific Research" },
	{ "name": "Product Development" },
	{ "name": "Market Research" },
	{ "name": "Clinical Trials" },
	{ "name": "Innovation Management" },
	{ "name": "Public Sector" },
	{ "name": "Government Administration" },
	{ "name": "Policy Analysis" },
	{ "name": "Public Health" },
	{ "name": "Nonprofit Management" },
	{ "name": "Community Services" },
	{ "name": "Real Estate" },
	{ "name": "Property Management" },
	{ "name": "Real Estate Sales" },
	{ "name": "Construction Management" },
	{ "name": "Architecture" },
	{ "name": "Interior Design" },
	{ "name": "Urban Planning" },
	{ "name": "Transportation" },
	{ "name": "Logistics Management" },
	{ "name": "Supply Chain Analysis" },
	{ "name": "Freight and Shipping" },
	{ "name": "Warehousing" },
	{ "name": "Energy" },
	{ "name": "Renewable Energy" },
	{ "name": "Oil and Gas" },
	{ "name": "Utilities" },
	{ "name": "Nuclear Energy" },
	{ "name": "Mining" },
	{ "name": "Telecommunications" },
	{ "name": "Network Engineering" },
	{ "name": "Telecom Sales" },
	{ "name": "Customer Support" },
	{ "name": "Media and Entertainment" },
	{ "name": "Broadcasting" },
	{ "name": "Journalism" },
	{ "name": "Publishing" },
	{ "name": "Gaming" },
	{ "name": "Animation" },
	{ "name": "Sports Management" },
	{ "name": "Fitness Training" },
	{ "name": "Coaching" },
	{ "name": "Sports Medicine" },
	{ "name": "Agriculture" },
	{ "name": "Farming" },
	{ "name": "Agribusiness" },
	{ "name": "Horticulture" },
	{ "name": "Animal Husbandry" },
	{ "name": "Food Production" },
	{ "name": "Environmental Services" },
	{ "name": "Waste Management" },
	{ "name": "Recycling" },
	{ "name": "Environmental Consulting" },
	{ "name": "Sustainability" },
	{ "name": "Forestry" },
	{ "name": "Cloud Computing" },
	{ "name": "DevOps" },
	{ "name": "Artificial Intelligence" },
	{ "name": "Machine Learning" },
	{ "name": "Blockchain" },
	{ "name": "Internet of Things (IoT)" },
	{ "name": "Augmented Reality (AR)" },
	{ "name": "Virtual Reality (VR)" },
	{ "name": "Robotics" },
	{ "name": "Network Security" },
	{ "name": "Mobile Development" },
	{ "name": "E-commerce" },
	{ "name": "Business Intelligence" },
	{ "name": "Enterprise Resource Planning (ERP)" },
	{ "name": "Customer Relationship Management (CRM)" },
	{ "name": "Business Analysis" },
	{ "name": "Project Coordination" },
	{ "name": "Operations Management" },
	{ "name": "Strategic Planning" },
	{ "name": "Consulting" },
	{ "name": "Entrepreneurship" },
	{ "name": "Product Management" },
	{ "name": "Risk Management" },
	{ "name": "Change Management" }
]
	;
(async () => {
	try {

		await prisma.jobCategory.createMany({
			data: categories,
			skipDuplicates: true // Optional, if you want to avoid duplicates
		});

		console.log("Job categories inserted successfully.");
	} catch (error) {
		console.error("Error inserting job categories:", error);
	} finally {
		await prisma.$disconnect();
	}
})();
